spring:
datasource:
url: jdbc:mysql://localhost:3306/heatcaution?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
username: root
password: your_pw
jpa:
hibernate:
ddl-auto: update   # ?? ???. ??? flyway ??
properties:
hibernate:
format_sql: true
jackson:
property-naming-strategy: SNAKE_CASE
